import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
const waltoGraph = localFont({
  src: "./fonts/waltograph42.ttf",
  variable: "--font-walto-graph",
  weight: "100 900",
});
/*
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
*/
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${waltoGraph.variable} ${waltoGraph.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
